### ISSUE TITLE
Design error on +5V net

### ISSUE THREAD

**Issue by HenrikBork** [prusa3d/MM-control-2.0#15] opened 2021-03-28 21:27 UTC
Hi,
There seems to be a bug in the design regarding the +5V net.
On my MMU2 i measured 4.2V on the +5V, which is too little for the MCU to run 16MHz. This is seemed to be the reason why my MMU was almost unusable as the MCU resets all the time.
Connecting the usb to a host helped a little on stabillity (and the +5V voltage rose 50-100mV)
I have shorted D1 on the MMU PCB, as a "proof-of-problem", and that raised the voltage to 4.8V and removed all MMU misbehavings. (without the usb connected). In the same bug chasing i also added 1000uF between the shorted D1 and GND. I think C59 was probably just fine as it is. (i was tiered of bug chasing the MMU)
**Please note: this is not a proposal to a solution, just "proof" of some kind of an issue with the +5V (at least on my MMU). I have no understanding of the diode's function in the entire printers power nets.** -although this hack has been working for some time now.

So it seems as if the designer was aiming for generating +5V by means of the TMC2130. But forgot to connect the VSA to >6V. But then again why differ so much from the suggested circuit and component values?...
The solution of using the printers +5V through a diode and a inductor yields too low a voltage.
...so it seems as the +5V was forgotten, but it somehow sometimes almost works...

My hope is that Prusa fix this problem in the hardware design. (and sends me a fixed PCB free of charge ;-)

### Henrik B. S.

My setup:
Original Prusa I3MK3 (2-3 years old), since then upgraded with factory parts.
MMU2 bought from Prusa around august 2020.
MMU PCB reads "2019-09 rev 0.4.4"
My ugly hack:
![MMU_PSU_BUG_20210328_132014](https://user-images.githubusercontent.com/54251874/112757923-068eae80-8fec-11eb-93f2-2adc71dd4c64.jpg)

extra info:
I also reported/discussed this on [https://forum.prusaprinters.org/forum/original-prusa-i3-mmu2s-mmu2-hardware-firmware-and-software-help/i-found-serious-design-error-in-mmu2-electronics-hardware/#post-405106](https://forum.prusaprinters.org/forum/original-prusa-i3-mmu2s-mmu2-hardware-firmware-and-software-help/i-found-serious-design-error-in-mmu2-electronics-hardware/#post-405106)
...My daytime job is to do this kind of work as consultant - so next time just hire me :-)

**Comment by Chrismettal** [comment] 2021-05-22 16:36
Can confirm, my board started to reset every time it needed to unload filament, getting stuck and requiring user input on every single filament change.
Bypassing the diode raised the 5 V rail from 4.6 V to 4.95 V in idle, fixing the resetting issue for now. Before I could see dips under 4.5 V on the rail on filament changes at which point the MCU sometimes reset. 

The capacitor does not seem to be required for me, but I have also added the missing decoupling caps on the shift registers, which were required for my unit to home correctly without crashing into the left wall, misaligning everything.

Thank you for your find and I sincerely hope Prusa did not abandon the MMU2 and are going to release a new version of the board (Or maybe at least publish the sources of the most recent version since this repo is behind the actually released boards)

**Comment by ANTALIFE** [comment] 2022-01-03 07:58
Good catch! Looks like quite a big HW bug...

![Screenshot 2022-01-03 185741](https://user-images.githubusercontent.com/21979291/147909347-65a4701a-4c58-4e52-b270-d33708fbb4bd.png)


**EDIT:** Just had a closer look at schematic and looks like designer accidently ignored the voltage drop across the reverse polarity protection diode (D1), polyfuse (F1), as well as the cable running between MK3S RAMBo & MMU2 PCBA. Would have been better to generate the +5V from the +24V rail coming in, that way there is no pesky voltage drops

![Screenshot 2022-01-03 192005](https://user-images.githubusercontent.com/21979291/147910735-62015a5a-b3eb-4cf2-819c-1183428cda6b.png)

**Comment by ChrisPetit** [comment] 2022-06-20 11:52
it has been a year...is this being addressed? I haven't had a correct functioning MMU2S since it was first released...

**Comment by Kugelfang666** [comment] 2022-06-20 15:25
Same problem with me, adding a 5V USB PSU to the MMU reduced the frequency of this problem coming up but it still happens every now and then

**Comment by lemmingDev** [comment] 2022-08-27 14:30
So, is there a verified fix for this hardware issue yet?

**Comment by Kugelfang666** [comment] 2022-08-27 15:38
Yep, adding a stepdown  to provide the 5V line of the 12 line permanently fixed the issue for me. Check out the tread in the Prusa Forum. All the details are there an I can verify that this is working. Did a multicolor print yesterday and not a single problem!

**Comment by vladimir-aubrecht** [comment] 2022-09-07 14:16
@ok1hra Do you think you could help with some official statement on this issue?

I think any answer would be better than none as it's keeping people in a void of not knowing if it make sense to wait for some kind of official fix (or even new version of the board) or they should just try to fix it themselves/sell mmu2s/...

Unfortunately I started to hit this issue too 😕

**Comment by JakoobCZ** [comment] 2022-10-04 18:50
Hi,
sorry for the late response. We are working on updates to the MMU2S. Our devs are finalizing new smarter firmware, which will bring new features along with improved performance and reliability to the MMU2S - all on the current motherboard. The new firmware is being tested on multiple printers and so far the results look very promising - we're focusing on the elimination of restarts caused by low voltage, reducing required user interventions and overall better user experience. I can't promise any ETA, but we are doing our best to have it done as soon as possible.

**Comment by Chrismettal** [comment] 2022-10-05 16:21
This is great news and I am extremely grateful for an update. Thank you!
A little communication goes a long way, and sharing any progress helps users keep faith in the project.

Can you share the reason why development isn't done in a publically visible branch? Even having the actually released board revision visible here would be an upgrade, as the repo seems to be lagging behind the actually available product version.

**Comment by banhuk** [comment] 2022-10-26 12:46
Great news - Happy to beta test this new firmware.  Keep the updates/communication coming!

**Comment by Ro3Deee** [comment] 2023-03-08 19:20
Related? 
https://github.com/prusa3d/Prusa-Firmware/pull/4069

**Comment by GRIFFCOMMca** [comment] 2023-06-03 00:55
I have arrived here as the 2019 MK3s with the MMU2s seems to have the same issue, many resets, this only really started to happen recently, we have not modified the printer, we have a Pi Zero, which was upgraded to a Pi Zero 2 in the past 4 months, we found it abit better when moving the data cables for the front LCD away from the data cable from the MMU2s, still has MANY issues with constant resets resulting in 5 green / orange flashing LEDs,

How is the firmware coming as this is really now unusable.

**Comment by dtryba** [comment] 2023-07-30 20:31
> How is the firmware coming as this is really now unusable.

The new firmware is out and the results is that it worsened this bug.

I had this issue when I installed a switch to the MMU2S to easily disable it, so remove the switch again.
The MMU2S worked fairly well with older stock, it worked fine with The Zero Beast firmware. With 3.0.13 and MMU3_3.0.0+814.hex the MMU2S became unworkable. Power issues resulting in "MMU MCU ERROR 04306" and ""MMU SELFTEST FAILED 04325", followed by "IDLER CANNOT HOME 04125" when it got past the first 2. 

Shorting the diode didn't resolve these issues. So that finally drove me to install a DC-DC boost converter between the printer and pin 1. Ramping up the voltage after the diode to 4.9V appears to have given me a workable MMU2S again.

Version of MMU board: 0.3 producion date 2018-04-2x.

The MMU3 manual just went live. The controller board looks the same (based on the images only), but the solution to this power issue is visible in step 25: PD-board https://help.prusa3d.com/guide/6-pulley-body-assembly_328918#392721
Power Distribution?

**Comment by JanMrlth** [comment] 2023-08-05 19:41
I updated the MK3s+ to 3.13.0-6873 and the MMU2S to 3.0.0 with the result, that I get a 'MMU MCU ERROR 04306' all the time.

**Comment by puckpuck** [comment] 2023-09-09 01:34
I suspect a power problem with my MMU2S after over 2 years of hassle-free usage. Waiting for the new firmware, I finally had time to try it out, and upon first boot, I get the 04306 error.

So, this feels like a hardware issue now. Is Prusa able to help here? Is my only option to buy another MMU mainboard and wait for it to ultimately fail on me again?

**Comment by Ro3Deee** [comment] 2023-09-29 16:15
>Is Prusa able to help here? Is my only option to buy another MMU mainboard and wait for it to ultimately fail on me again?

@davidkerny  comment from his [Ultimulti Mod ](https://www.printables.com/model/537888-mmu3-ultimulti-printable-parts/comments/1092379): 
_”It might help but the best solution available is the small board found in the MMU3 upgrade, the PD-board addon. Not only it makes the 5V supply for the logic circuits more stable, but also provides some improvements for a more stable communication to the printer. There is a diode that cuts off voltage peaks and better shielding in the cable against interference. More easily accessible quick-release connector on the cable being a small bonus._
_The 5V supply to the MMU is a bit on the edge. If you inspect the TMC 2130 datasheet, there are several suggested ways to wire them up. The way it is done on MMU board is correct - only if supplied with a precise external 5V power. If you see the MMU2S diagrams, the 5V + is fed to the MMU logic from Einsy via the blue cable and through the D1 diode (with a certain voltage drop of approx. 0.3V) and the F1 polyfuse (with a possibly unpredictable voltage drop, usually around 0.2V).If there is a voltage drop in the cable/connections, there might not be enough voltage for the TMC driver's charge pump to operate correctly and the driver restarts or even shuts off to prevent a catastrophic failure. An extreme 5V VCC undervoltage is detected by the fiwmware 3.x.x on startup - and the MMU MCU ERROR is shown. On the previous firmware, 1.0.6, the TMC shutting off manifests itself as all the LEDs blinking. TMC restart used to be just ignored by the FW and there were just no sophisticated methods of detecting these states, nor displaying them to the user"_

**Comment by SixOThree** [comment] 2023-09-29 19:32
Before finding information suggesting a design issue I replaced that MMU mainboard (at my own expense). Then I replaced all of the stepper motors, one by one, again at my own expense. I worked with tech support and posted on and created multiple threads with no suggestion there is a mainboard design issue. Not particularly please with what I am seeing.

**Comment by jfestrada** [comment] 2023-10-02 08:17
Last week I asked to the support about the possibility to buy the PD-Board, they told to me that the PD-Board was only available for the upgrade kits (100€) or new MMU3 purchases, so I'm very angry as a customer because they sold a faulty design and now @josefprusa refuse to sell (not even give as warranty) to the original mmu2s owner the possible solution. So, first will be the new customers and later maybe the old customers. As a customers we should do more noise on social networks because this is a very bad behavior from @josefprusa and @prusa3d with us.

Anyway recently I released an MMU3 version for 10 colors and I found that I could get rid of some MCU errors related with the input current if I change the range for the critical error, of course is not a solution but make the MMU2S with the 3.0.1 firmware more usable, here is the repository [CM3D-Firmware-MMU](https://github.com/ComunidadMaker3D/CM3D-Firmware-MMU)
This is what I changed on the config.h file from 274 to 300. 
![image](https://github.com/prusa3d/MM-control-2.0/assets/7290345/84d8a68b-46e9-483c-87f3-ccd3087bc9f9)

**Comment by Ro3Deee** [comment] 2023-10-02 08:42
If prusa will not sell us the pd board, someone will: 
 Blurolls Prusa I3 MK3 Multi Material 3.0 MMU3  MMU PD-board Addon with Cable for MMU3 Prusa I3 MK3S MK3S+
https://a.aliexpress.com/_ms5aJtk

**Comment by jfestrada** [comment] 2023-10-02 10:15
I saw that item, but it currently doesn't have a fair price,30$ is to high for a PD-Board at least for me. Because of that I asked to the @Prusa3d support again, and they said that their priority are the upgrade and new kits. Also they are selling it as a new product and I suppose that's because this way they are avoiding to take care of any possible warranty with the customers of the MMU2S. 
So, they took many improvements made by the people because the Open Source, then fixed the issue on the original design with a new board, and release a fw which is not usable without that board, and also they refuse to sell to the MMU2S owners without buy an upgrade kit (100€). For me it's like a bad joke.

**Comment by Ro3Deee** [comment] 2023-10-03 17:10
I don't have the pd board and mmu3 fw works on my mmu2 hardware (with shorted D1 diode)

**Comment by JakoobCZ** [comment] 2023-10-03 17:39
Hi,
If the new firmware 3.0.0 (or newer) is causing issues, please get in touch with our support team to discuss your case and troubleshoot the problem (fastest way: livechat at [prusa3d.com](http://prusa3d.com/)). We can then provide the necessary parts - even a replacement main MMU board if needed and/or a free voucher for the MMU2S->MMU3 upgrade kit, which includes the PD board addon and cable. [Check our Prusa blog article](https://blog.prusa3d.com/original-prusa-mmu3-is-here-multi-material-printing-with-improvements-all-around-now-shipping_80485/) for more information.

Please let me know if you managed to get things sorted out 🙂

**Comment by jfestrada** [comment] 2023-10-04 08:21
> Hi, If the new firmware 3.0.0 (or newer) is causing issues, please get in touch with our support team to discuss your case and troubleshoot the problem (fastest way: livechat at [prusa3d.com](http://prusa3d.com/)). We can then provide the necessary parts - even a replacement main MMU board if needed and/or a free voucher for the MMU2S->MMU3 upgrade kit, which includes the PD board addon and cable. [Check our Prusa blog article](https://blog.prusa3d.com/original-prusa-mmu3-is-here-multi-material-printing-with-improvements-all-around-now-shipping_80485/) for more information.
> 
> Please let me know if you managed to get things sorted out 🙂

Hi @JakoobCZ , I have reported my issue this morning to the support chat, I'm currently waiting for the answer of the developers. Again, this is a faulty design. So let see what the developers say and which solution offer the support team.

**Comment by jfestrada** [comment] 2023-10-04 10:00
> I updated the MK3s+ to 3.13.0-6873 and the MMU2S to 3.0.0 with the result, that I get a 'MMU MCU ERROR 04306' all the time.

The way to avoid that loop is to modify the value of the VDCACCThreshold variable on the config.h file, I have tested with 300 which will allow 3.8V as minimum. Then build the firmware with utils/build.py script and flash your own version.

**Comment by SixOThree** [comment] 2023-11-03 03:12
Hi All. I have been hesitant to try the suggestions of altering the board. But I did order the MMU3 upgrade kit. And when it arrived I noticed it had a PD-board included. I decided to just give it a shot without using any other parts from the upgrade. After installing the PD-board my printer immediately started working. 

The mainboard is dangling out the back of the unit. But I can move the selector. I can load filament. I can switch to another filament slot and load a second filament there. Heck, I could probably load 5 filaments! I could probably run a multi-color print! 

I have changed no other parts than adding the pd-board.

During the last few years, I have spent countless hours debugging this MMU2 unit. I bought the MMU2S upgrade. I replaced the mainboard. I replaced all of the servos (edit: steppers) one by one. I replaced the cables (all before finding these threads mind you). 

The most I ever got out of this printer was 5 blinking lights. I considered myself lucky if I could even get a single color print to start. Never mind that they all ended with errors unloading the filament. I had maybe a 1 in 10 chance of resetting the unit and getting a filament to load. Just enough to fight the machine to get a print started. And I refused to convert the printer back to mono filament.

The frustration related to this makes me feel like prusa is not operating in good faith. And seeing this thing working with a little power board makes it all the worse. What I bought was not ever a working product. Replacing every part still resulted in a non-functional product. This MMU2 to MMU3 upgrade should have been free. That's all there is to it. 

This ordeal has 100% ruined the experience of using this printer and looking back, it really has destroyed the hobby for me.

**Comment by GRIFFCOMMca** [comment] 2023-11-03 05:28
Your move PRUSA, its easy, everyone even told you what to do...

**Comment by jfestrada** [comment] 2023-11-03 07:47
Definetly I agree with @SixOThree, @josefprusa sold to us a faulty design, and now they want to avoid the fix just selling it as an upgrade. I asked to the support three times, the last one I made the reference to @JakoobCZ and I have had no answer since then, they say to me that they will reach me with an answer but that never happen. So @josefprusa took from me almost 300€ for a faulty design, now years later they had say "ouch the design has an error" and instead of send the PD-Board to all the customers for free, @josefprusa pretends that we spend another 100€ on the upgrade kit. NO WAY, that's not going to happen, NEVER. I prefer to buy a Bambulab printer than another Prusa machine. Both are close source on electronics and pieces so where is the difference now? I feel very upset with this situation, and by now I will implement this solution --> https://www.printables.com/model/620818-mmu2-5-volt-power-fix?fbclid=IwAR2o2KFAJloaAzRCLWM-nIziLRyKihPp9WNVWtz4ps1AV6q5oigmXqDxc-s#preview which is easy and I can test it right now. So at least that @josefprusa change their mind about the PD-Board I will not recommend a Prusa machine anymore to anybody.

**Comment by jfestrada** [comment] 2023-11-03 13:53
It works. Now the firmware is not raising the error about the lack of voltage.

![image](https://github.com/prusa3d/MM-control-2.0/assets/7290345/94d2f685-4dbb-408a-8f7b-58ee198f7787)

**Comment by jfestrada** [comment] 2023-11-03 13:56
> It works. Now the firmware is not raising the error about the lack of voltage.
> 
> ![image](https://user-images.githubusercontent.com/7290345/280298602-94d2f685-4dbb-408a-8f7b-58ee198f7787.png)

@josefprusa do you belive that we as customers deserve this kind of DIY solutions?

**Comment by negroISO** [comment] 2023-11-16 19:37
Holly hell. One of the reasons I dumped my MK3S+ and MMU2S was this issue! It didn't happen at first but after a while, it just would reset all the damn time. Wouldn't feed filament, wouldn't retract it, just Bloop blink and reset. I need to check my board to see what's up.

**Comment by phat3r** [comment] 2023-12-03 05:30
Chris Riley found an easier way to get 5V ... move one pin ... and a 2 cent du-pont plug ... this has been going on for how long ... https://youtu.be/JAWqIH_U66s?si=WHZxiUF6VFchaMWd&t=1141

**Comment by puckpuck** [comment] 2023-12-05 23:21
> Chris Riley found an easier way to get 5V ... move one pin ... and a 2 cent du-pont plug ... this has been going on for how long ... https://youtu.be/JAWqIH_U66s?si=WHZxiUF6VFchaMWd&t=1141

I just did this... instead of finding a small connector, I used vinyl tape. It works like a charm, and I'm MMU printing right now after nearly 10 months of finicking with it and no MMU in operation.

**Comment by timolow** [comment] 2023-12-11 22:29
@JakoobCZ I contacted support today after my MMU refused to function anymore, got the run around, unable to sell me the PD board without the upgrade kit and said I have to pay full price for an "upgrade kit", As a person who bought the MMU1, MMU2, MMU2S this feels like a cash grab each time I have to pay money to make a product I already paid for work right.

**Comment by lemmingDev** [comment] 2023-12-12 01:24
Lucky AliExpress has you covered ;)
https://www.aliexpress.com/item/1005006221728533.html

**Comment by phat3r** [comment] 2023-12-12 01:45
$40 for part that isn't needed - value ... Just 5 minutes work to de-pin and move the blue wire over to the SPI as per Chris Riley suggestion above ... I have done it on both my MMU2's ... one a clone and one original prusa and has resolved all the power / logic nonsense.   If you want to make it super near ... use a 2c dupont connector - the pin will go into it.

**Comment by lemmingDev** [comment] 2023-12-12 05:04
Yeah - I personally used buck converters for my 3 when it was originally suggested, though if I were to do it again, I would do as above, and not spend any money...

**Comment by eoyilmaz** [comment] 2023-12-28 16:28
> It works. Now the firmware is not raising the error about the lack of voltage.
> 
> ![image](https://private-user-images.githubusercontent.com/7290345/280298602-94d2f685-4dbb-408a-8f7b-58ee198f7787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODExMDYsIm5iZiI6MTcwMzc4MDgwNiwicGF0aCI6Ii83MjkwMzQ1LzI4MDI5ODYwMi05NGQyZjY4NS00ZGJiLTQwOGEtOGY3Yi01OGVlMTk4Zjc3ODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjhUMTYyNjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY0MTg3NGE1MWU3OTYwM2I4ZmMzZjVhYzNkOWVhNmUwNTBjYmNlY2I1YTRkMTRlNjBmZjIyN2RkYWZmMDY0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rpMkzBcZem4LEWwm9EMtWDEy0gDL9Ts4G84DZBDtYas)

Hey, isn't this the 10 color version :)

**Comment by roster210** [comment] 2024-04-05 04:33
This is outrageous we all had faith with them as a company and they have known about this issue and not addressed it for years and the fact the fix is so easy is out of this world, Josef Prusa obviously only cares about more money, they have enough resources to cover this issue, the profit margins on this non working device are out of this world and they still push the issue so  far and do not address it or release a fix until after most peoples or all peoples warrantys are void. I own two and have for years and they are decent printers but that is not a decent company, they have multiple firmware versions that have fried boards then dont honor that fix unless you are in your 1 year warranty range and then they have this.  they have their propritary einsy rambo that is just a pain to  deal with compared to ulti's or even any knock off chinese ones. in hindsight it feels obvious they only care about themselves and Josef, mostly josef and it feels obvious because of the multiple pictures of his arrogant face and the namesake the company. I am not surprised that they evade the issue by ignoring knowledge of it, they seem to b e better at it then the chinese manufactured ones- who have replaced components just off proof of sales, its outrageous this overpriced machine does not give the support you would assume you should get for a $1100 setup at the time. We spend 1000 and prusa cant give us something that costs them <$5 to be able to use our machine. I am going to make as much noise as i canabout this online, its outrageous that this is all it needed and they held onto it until mmu3... on the positive side- i now know a lot more about printers because of fixing and trying to fix this and other issues. Ill never buy a prusa from prusa again and ill  never buy one unless its 1/4 of their price, ill never give that man or his company money again they do not deserve it 300$ for printed plastic and 3 steppers that i had to put together is highway robbery and then it doesnt even work...

**Comment by lemmingDev** [comment] 2024-04-06 06:42
Yeah - I feel your pain 

For my school, I suggested we buy 7 x MK3S and 3 x MMU2S a number of years ago
We were never able to get the MMU2S working at all and just removed them

Over the years I tried many different 3D parts from DIYers to fix the issues, but it hasn't been until recently when the DIY power fix was worked out that they've now been able to be actually used semi-reliably

I'm in charge of purchasing and we won't be buying Prusa when they're due to be replaced due to this fiasco

The MK3S machines we bought have been fairly reliable and I've been able to maintain them
A Y stepper on an Einsy died a year ago and I replaced it with a clone Einsy off AliExpress
An MMU board died too, and I replaced it with one off AliExpress too
A few heater cartridges, thermisters, PINDA and fans have also had to be replaced

**Comment by Prusa-Support** [comment] 2024-05-07 16:09
Hi everyone and thank you all for sharing.

The minimum required voltage for the MMU is around 4.5V. Users with lower voltage may be able to identify the cause by troubleshooting for hardware problems. The cause is oftentimes a partially damaged cable, a pulled wire inside the connector, or a loose connection. Such faults, or others, may be reported to our Customer Support. While a correctly assembled MMU can function with ~4.5-5V, if some assembly issues are present, its reliability may be affected negatively - e.g. excess friction from misaligned parts, over-tightened bolts, restricted filament paths... 

Over the years, we have been able to solve virtually all problems directly reported and followed up with our Customer Support whereas, in case of even unnoticeable cables/boards problems, warranty replacements have solved these issues. For this reason, we have encouraged everyone with unresolved issues, who contacted us in the warranty period, to give us another opportunity to make this right. It is our hope to help everyone, with any issue, to solve the problems once and for all. In most cases, checking the connection and the wires, or re-printing a few parts, solved the problem but our special deal also included the possibility to get an upgrade voucher beyond the warranty terms.
https://blog.prusa3d.com/original-prusa-mmu3-is-here-multi-material-printing-with-improvements-all-around-now-shipping_80485/

While we do offer the [PD-board on our eshop](https://www.prusa3d.com/en/product/mmu-pd-board-addon/), which may help to overcome some hardware, connection, or assembly-related issues; the PD-board does not correctly address all of these issues and it is officially only compatible with the MMU3 specific parts. We would also like to point out that the new firmware is better at detecting potential problems, and improves user interaction regardless of the additional PD-board.

We hope this may satisfactorily address the issue but please keep your precious feedback coming, here or via official support channels. However, our best recommendation remains to consult our Customer Support, always available for you, 24/7, by chat and email.

Michele Moramarco
Prusa Research

**Closed as completed** 2024-05-07 19:17 UTC
